version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - DB_HOST=db
      - DB_DATABASE=news_aggregator
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]  # Check the internal port (80)
      interval: 30s
      retries: 3

  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: news_aggregator

    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  dbdata:
